<?php
$deliveries = $block->getOrderDeliveryForDate();
?>
<form id="search_order" action="<?php echo $block->getBaseUrl();?>dailycoco_manage/dailycocoadmin/orderdelivery/search" method="POST">
<div class="row">
    <br/>
    <br/>
</div>
<table>
    <tr>
        <td>
            <select name="status">
                <option value="Delivered">Delivered</option>
                <option value="Delivered but missed">Delivered but Missed</option>
            </select>
        </td>
        <td> &nbsp; &nbsp;
        </td>
        <td>
            <input name="form_key" type="hidden" value="<?php echo $block->getFormKey(); ?>" />
            <input type="hidden" name="searchddate" value="<?php echo $block->getOrderDeliveryDate(); ?>">
            <button class="button" type="submit">Change Delivery Status</button>
        </td>
    </tr>
</table>
<div class="admin__table-wrapper">
    <table class="data-table admin__table-primary edit-order-table">
        <thead>
            <tr class="headings">
                <td>

                </td>
            	<td>
            		<b>Product</b>
            	</td>
            	<td>
            		<b>Quantity</b>
            	</td>
            	<td>
            		<b>Address</b>
            	</td>
            	<td>
            		<b>Pincode</b>
            	</td>
            	<td>
            		<b>Delivery Status</b>
            	</td>
            </tr>
        </thead>
        <tbody>
        	<?php $i =1;
                foreach($deliveries as $delivery) {?>
        		<tr>
                    <td>
                        <input class="admin__control-checkbox" type="checkbox" name="statusupdate[]" value="<?php echo $delivery['order_delivery_id'];?>" id="id<?php echo $i;?>"/>
                        <label for="id<?php echo $i;?>"></label>
                    </td>
        			<td>
        				<?php echo $delivery['product_sku'];?>
        			</td>
        			<td>
        				<?php echo $delivery['quantity'];?>
        			</td>
        			<td>
        				<?php echo $delivery['address'];?>
        			</td>
        			<td>
        				<?php echo $delivery['postcode'];?>
        			</td>
        			<td>
        				<?php echo $delivery['delivery_status'];?>
        			</td>
        		</tr>
        	<?php $i++;
            }?>
        </tbody>
    </table>
</div>
</form>