<div class="container">
	<div class="row">
		<p>
			Believing in the philosophy that many diseases or health issues wouldn’t even be around if
we chose to embrace the natural products &amp; consumed them in their freshest form. With an
intent to change people’s lifestyle in a positive way, we decided to procure top-quality
tender coconuts right from the farms, and deliver them to your doorsteps.
		</p>
		<p>
			The brainchild of two tech-savvy individuals, Daily Coco was also started with a vision to
uplift the farming community, and with our dedicated field team, which is always on the
lookout for some of the best farms growing the top-notch tender coconuts, we are quite
confident about our sources and the quality of coconuts. All our coconuts are sourced from
the choicest lush farms around Mysore, Hassan &amp; Tumakuru region.
		</p>
		<p>
			Notably, Daily Coco tender coconut water is 100% natural with no preservatives, added
sugar, and is delivered in a natural state, without the plastic pre-packaging hullabaloo.
		</p>
		<p>
			Get your daily refreshment fix or hydration dose, rich in vitamins, minerals &amp; electrolytes,
etc., in the comfort of your home, just alongside your morning paper, and that too at no
extra delivery charges — presenting Daily Coco, your personal provider of delectable, tasty,
and healthy tender coconut water.
		</p>
		<p>
			Subscribe to the flavourful and nourishing nature’s elixir TODAY — say YES to health and
wellness!
		</p>
	</div>
	<div class="row justify-content-center">
		<p>
			Even a Coconut a Day can help keep the doctor away – stay healthy &amp; fit almost<br/>effortlessly!
		</p>
	</div>
</div>