<?php

/**
 * @var \Dailycoco\Dcapp\Block\ProductDelivery $block
 */

$prdDelivery = $block->getAllOrdersByCustId();

?>
<div class="container">
	<div class="row">
		
		<div class="rowtitlehead col-lg-3 col-md-3">
			Product 
		</div>
		<div class="rowtitlehead col-lg-3 col-md-3">
			Quantity 
		</div>
		<div class="rowtitlehead col-lg-3 col-md-3">
			Delivery Date
		</div>
		<div class="rowtitlehead col-lg-3 col-md-3">
			Status
		</div>
	</div>
	<?php foreach($prdDelivery as $prdData) {?>
	<div class="row">
		
		<div class="col-lg-3 col-md-3">
			<?php echo $prdData['product_sku']; ?>
		</div>
		<div class="col-lg-3 col-md-3">
			<?php echo $prdData['quantity']; ?>
		</div>
		<div class="col-lg-3 col-md-3">
			<?php echo $block->convertGivenDate($prdData['delivery_date']); ?>
		</div>
		<div class="col-lg-3 col-md-3">
			<?php echo $prdData['delivery_status']; ?>
		</div>
	</div>
	<?php }?>
</div>