<div class="container" style="padding: 15px 0px;">
	  <a class="navbar-brand" href="/">
	  	<img src="<?php echo $this->getViewFileUrl('images/logo1.png'); ?>" alt="DailyCoco Logo" width="189" height="70">
	  </a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>			
</div>