<!-- start banner Area -->
<section class="banner-area relative" id="home" data-parallax="scroll" data-image-src="<?php echo $this->getViewFileUrl('images/dailycoco_parallax_img.jpg'); ?>">
	<div class="overlay-bg overlay"></div>
	<div class="container">
		<div class="row fullscreen  d-flex align-items-center justify-content-end">
			<div class="banner-content col-lg-6 col-md-12" style="height: 350px;">
				<h1>
					<br/>
					<br/>
					<br/>
					<br/>
				</h1>
				<!--h1>
					Tender Coconut <br>
					Delivered <span>EveryDay</span>							
				</h1-->
			</div>												
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- start howtoorder Area-->
<section class="service-area pt-70 pb-40" id="howtoorder">
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="menu-content pb-40 col-lg-8">
				<div class="title text-center">
					<h1 class="mb-10">How to Order</h1>
					<!--p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore  et dolore magna aliqua.</p-->
				</div>
			</div>
		</div>	
		<div class="row">
			<div class="sigle-service col-lg-4 col-md-6">
				<img src="<?php echo $this->getViewFileUrl('images/subscribe.png'); ?>" style="height:69px;"/>
				<h4>Subscribe</h4>
				<p>
					Simply choose a subscription plan you like and enter your basic details.
				</p>
				<!--a href="#" class="text-uppercase primary-btn2 primary-border circle">View Details</a-->
			</div>
			<div class="sigle-service col-lg-4 col-md-6">
				<img src="<?php echo $this->getViewFileUrl('images/Scheduledelivery.png'); ?>" style="height:69px;"/>
				<h4>Schedule Delivery</h4>
				<p>
					Set Vacation / Pause Delivery as per your convenience.
				</p>
				<!--a href="#" class="text-uppercase primary-btn2 primary-border circle">View Details</a-->
			</div>
			<div class="sigle-service col-lg-4 col-md-6">
				<img src="<?php echo $this->getViewFileUrl('images/WeDeliver.png'); ?>" style="height:69px;"/>
				<h4>We Deliver</h4>
				<p>
					We will have your tender coconuts delivered at your doorstep before 7:30 am
				</p>
				<!--a href="#" class="text-uppercase primary-btn2 primary-border circle">View Details</a-->
			</div>
		</div>
	</div>	
</section>
<!-- end howtoorder Area-->

<!-- start whyus Area-->
<section class="service-area pt-10 pb-40" id="whyus">
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="menu-content pb-40 col-lg-8">
				<div class="title text-center">
					<h1 class="mb-10">Why us</h1>
					<!--p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore  et dolore magna aliqua.</p-->
				</div>
			</div>
		</div>	
		<div class="row">
			<div class="sigle-service col-lg-4 col-md-6">
				<img src="<?php echo $this->getViewFileUrl('images/GuaranteedFreshness.png'); ?>" style="height:69px;"/>
				<h4>Guaranteed Freshness</h4>
				<p>
					We bring you farm fresh and the finest hand picked tender coconuts, that carries a good amount of water and taste.
				</p>
				<!--a href="#" class="text-uppercase primary-btn2 primary-border circle">View Details</a-->
			</div>
			<div class="sigle-service col-lg-4 col-md-6">
				<img src="<?php echo $this->getViewFileUrl('images/Hygiene.png'); ?>" style="height:69px;"/>
				<h4>Hygiene</h4>
				<p>
					We take extra care to handle all coconuts under hygienic conditions . After the coconuts are trimmed they are repeatedly washed with RO purified water before delivery. A better option than the roadside coconut vendor vendor.
				</p>
				<!--a href="#" class="text-uppercase primary-btn2 primary-border circle">View Details</a-->
			</div>
			<div class="sigle-service col-lg-4 col-md-6">
				<img src="<?php echo $this->getViewFileUrl('images/contactus.png'); ?>" style="height:69px;"/>
				<h4>Dedicated Support (Call / Whatsapp)</h4>
				<p>
					Our excellent customer care team is ready to assist you with any of your queries.
				</p>
				<!--a href="#" class="text-uppercase primary-btn2 primary-border circle">View Details</a-->
			</div>
		</div>
	</div>	
</section>
<!-- end whyus Area-->