<!-- start banner Area -->
<section class="banner-area relative" id="home" data-parallax="scroll" data-image-src="<?php echo $this->getViewFileUrl('images/dailycoco_parallax_img.jpg'); ?>">
	<div class="overlay-bg overlay"></div>
	<div class="container">
		<div class="row fullscreen  d-flex align-items-center justify-content-end">
			<div class="banner-content col-lg-6 col-md-12">
				<h1>
					Tender Coconut <br>
					Delivered <span>EveryDay</span>							
				</h1>
			</div>												
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- start service Area-->
<section class="service-area pt-100 pb-150" id="service">
	<div class="container">
		<div class="row d-flex justify-content-center">
			<div class="menu-content pb-70 col-lg-8">
				<div class="title text-center">
					<h1 class="mb-10">How Delivery Works!</h1>
					<!--p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore  et dolore magna aliqua.</p-->
				</div>
			</div>
		</div>	
		<div class="row">
			<div class="sigle-service col-lg-4 col-md-6">
				<span class="lnr lnr-rocket"></span>
				<h4>Easy Flight Search</h4>
				<p>
					inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct.
				</p>
				<a href="#" class="text-uppercase primary-btn2 primary-border circle">View Details</a>
			</div>
			<div class="sigle-service col-lg-4 col-md-6">
				<span class="lnr lnr-magic-wand"></span>
				<h4>Get Hotel Offers</h4>
				<p>
					inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct.
				</p>
				<a href="#" class="text-uppercase primary-btn2 primary-border circle">View Details</a>
			</div>
			<div class="sigle-service col-lg-4 col-md-6">
				<span class="lnr lnr-gift"></span>
				<h4>Holiday Packages</h4>
				<p>
					inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct.
				</p>
				<a href="#" class="text-uppercase primary-btn2 primary-border circle">View Details</a>
			</div>
		</div>
	</div>	
</section>
<!-- end service Area-->