<?php

/**
 * @var \Dailycoco\Dcapp\Block\ProductDelivery $block
 */

$vattest = $block->sayHello();



foreach ($vattest->getAllItems() as $item) {
	$productName = $item->getName();
	echo $productName," -- Name of the PRoduct <br/>";
   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
   $product = $objectManager->create('Magento\Catalog\Model\Product')->load($item->getId());
   echo $product->getData('product_days');
   echo "<br/>Quantity".$item->getQtyOrdered()."<br/>";
}

echo $block->deliveryStartDate();